### ISSUE TITLE
Mapper is not abstract exception on basic mapping when building

### ISSUE THREAD

**Issue by kjq** [mapstruct/mapstruct#3666]
### Expected behavior

Upgrading to 1.6.0 (and trying 1.6.0.RC) and running an install we get this error for a pretty basic mapping that worked using 1.5.5.Final. Nothing about this or the config seems to relate to any of the breaking changes and other mapping up until this are generated (which are far more complex).

```java
@Mapping(target = ".", source=".")
ClusterInstance mapInstance(InstanceConfig config, PipelineRun pipeline);
```

We are using:
- Quarkus (latest)
- Lombok (latest)
- Maven (latest)
- JDK 21

### Actual behavior

An exception is thrown when install is run...

```
[ERROR] /services/cluster/target/generated-sources/annotations/TektonMapperImpl.java:[23,1] TektonMapperImpl is not abstract and does not override abstract method mapInstance(InstanceConfig,io.fabric8.tekton.pipeline.v1beta1.PipelineRun) in TektonMapper
```

### Steps to reproduce the problem

1. Upgraded to 1.6.0
2. Run mvn install

### MapStruct Version

1.6.0

**Comment by kjq** [comment]
As a follow up I enabled the mapstruct verbose/debugging output and see this...

```
[INFO]  MapStruct: processing: services.cluster.tekton.TektonMapper.
[INFO]  MapStruct: applying mapper configuration: MappableConfig.
[INFO] - MapStruct: creating bean mapping method implementation for internal.cluster.ClusterInstance mapInstance(services.cluster.models.InstanceConfig config, io.fabric8.tekton.pipeline.v1beta1.PipelineRun pipeline).
[INFO] - MapStruct: creating bean mapping method implementation for services.cluster.models.Pipeline mapPipeline(io.fabric8.tekton.pipeline.v1beta1.PipelineRun run).
[INFO] -- MapStruct: mapping property: runMetadataName( run ) to: setPipeline(java.lang.String).
[INFO] -- MapStruct: selecting property mapping: runMetadataName( run ).
[INFO] -- MapStruct: mapping property: runSpecParams( run ) to: setParams(java.util.List<java.util.Map<java.lang.String,java.lang.Object>>).
[INFO] -- MapStruct: selecting property mapping: java.util.List<java.util.Map<java.lang.String,java.lang.Object>> #mapParams(runSpecParams( run )).
[INFO] -- MapStruct: mapping property: runStatusStartTime( run ) to: setStartTime(java.lang.String).
[INFO] -- MapStruct: selecting property mapping: runStatusStartTime( run ).
[INFO] -- MapStruct: mapping property: runStatusCompletionTime( run ) to: setCompletionTime(java.lang.String).
[INFO] -- MapStruct: selecting property mapping: runStatusCompletionTime( run ).
[INFO] -- MapStruct: mapping property: runStatusConditions( run ) to: setExtra(java.lang.Object).
[INFO] -- MapStruct: selecting property mapping: runStatusConditions( run ).
[INFO] -- MapStruct: mapping property: runSpecPipelineRefName( run ) to: setType(java.lang.String).
[INFO] -- MapStruct: selecting property mapping: runSpecPipelineRefName( run ).
[INFO] - MapStruct: creating iterable mapping method implementation for java.util.List<java.util.Map<java.lang.String,java.lang.Object>> mapParams(java.util.List<io.fabric8.tekton.pipeline.v1beta1.Param> value).
[INFO] -- MapStruct: selecting element mapping: java.util.Map<java.lang.String,java.lang.Object> #asMapParam(param).
[INFO] /cluster/src/main/java/services/cluster/ClusterOperations.java: /cluster/src/main/java/services/cluster/ClusterOperations.java uses or overrides a deprecated API.
[INFO] /cluster/src/main/java/services/cluster/ClusterOperations.java: Recompile with -Xlint:deprecation for details.
[INFO] /cluster/src/main/java/services/cluster/InstanceResource.java: /cluster/src/main/java/services/cluster/InstanceResource.java uses unchecked or unsafe operations.
[INFO] /cluster/src/main/java/services/cluster/InstanceResource.java: Recompile with -Xlint:unchecked for details.
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR :
[INFO] -------------------------------------------------------------
[ERROR] /cluster/target/generated-sources/annotations/services/cluster/tekton/TektonMapperImpl.java:[21,1] services.cluster.tekton.TektonMapperImpl is not abstract and does not override abstract method mapInstance(services.cluster.models.InstanceConfig,io.fabric8.tekton.pipeline.v1beta1.PipelineRun) in services.cluster.tekton.TektonMapper
[INFO] 1 error
```

**Comment by kjq** [comment]
I just realized there is a mapping methods used to support coverting `Param` into a list of Maps, it might be related to this?

```
/**
     * Map pipeline params to  a list of maps
     */
    @Mapping(target = ".", source = ".")
    List<Map<String, Object>> mapParams(List<Param> value);

    /**
     * Convert params to map
     */
    default Map<String, Object> asMapParam(Param value) {
        final Map<String, Object> m = new HashMap<>();
        m.put("name", value.getName());
        m.put("value", value.getValue());
        return m;
    }
```

**Comment by kjq** [comment]
Its something very distinct to that specific mapping but another mapping which uses _similar_ objects (`PipelineRun`) seems to be fine.

**Comment by filiphr** [comment]
The use of

```java
@Mapping(target = ".", source=".")
```

is really strange. It isn't quite clear what `source` is pointing to. Should be be `config` or `pipeline`. We don't really support `source = "."` and perhaps something broke in 1.6.

Nevertheless, it seems like we are not generating a compile error, but we are generating incorrect code. Can you perhaps provide the full mapper with the related classes so that we can try to find the root cause for this problem?

**Comment by kjq** [comment]
Thanks for the quick response.  I can try to see if I can create a reproducer but it is going to be painful because it is mapping classes from the Kubernetes/Tekton client.  I will say it is a pretty straight forward mapping as far as mappings go.

**Comment by filiphr** [comment]
@kjq a small repo that we can build should also be enough. You don't have to provide the classes in the issue. If you share a project with us that we can run (even with other dependencies) then it is more than enough

**Comment by filiphr** [comment]
Thanks @kjq, together with the 1.5.5.txt output you provided it should be enough. Will need some time to try to reproduce it.

How does the `MappableConfig` look like?

**Comment by kjq** [comment]
It could be that, im looking at the object returned and it does not even use that PipelineRun.  Im trying now.

**Comment by kjq** [comment]
Well that seemed to do it.  Im fine with closing this as not an issue since it was just a misuse o the `@Mapping`.  Probably code changed somewhere and it never got cleaned up.

I'm finding more like this one. I _think_ the assumption may of been that if the parameter name matched the target name it would be automatically handled unless explicitly stated (which is what it did before in 1.5.5)

So in the case below, everything in version would be mapped and instance would be mapped to the instance field.

```java
@Mapping(target = ".", source = ".")
abstract VersionResponse mapVersionResponse(Version version, List<ClusterInstance> instances);
```

Doing this resolves it and maps everything from version automatically and instances to the instances field.

```java
@Mapping(target = "instances", source = "instances")
abstract VersionResponse mapVersionResponse(Version version, List<ClusterInstance> instances);
```

**Comment by filiphr** [comment]
>I'm fine with closing this as not an issue since it was just a misuse o the `@Mapping`. Probably code changed somewhere and it never got cleaned up.

I'd like to figure out why we generated the invalid code. I'm not a fan that we are doing something like this.

>So in the case below, everything in version would be mapped and instance would be mapped to the instance field.
>```java
>@Mapping(target = ".", source = ".")
>abstract VersionResponse mapVersionResponse(Version version, List<ClusterInstance> instances);
>```

Oh wow, I didn't even realize that we are doing something like that. That most certainly worked by accident. 

>Doing this resolves it and maps everything from version automatically and instances to the instances field.
>```java
>@Mapping(target = "instances", source = "instances")
>abstract VersionResponse mapVersionResponse(Version version, List<ClusterInstance> instances);
>```

That is indeed how it should work.

**Comment by kjq** [comment]
Luckily for us only 2 places that occurred...
