### ISSUE TITLE
Not recognizing field in @Mapping with the newest Lombok (1.18.16)

### ISSUE THREAD

**Issue by mkczyk** [mapstruct/mapstruct#2271]
MapStruct doesn't recognize fields in `@Mapping` with the newest Lombok version 1.18.16 (in Java 11). But it works with older version 1.18.10.

Example: 

```
@Data
public class ExampleModel {
    private String someField;
    private String fieldInModel;
}
```

```
@Data
public class ExampleDto {
    private String someField;
    private String fieldInDto;
}
```

```
@Mapper(componentModel = "spring")
public interface ExampleMapper {

    @Mapping(target = "fieldInModel", source = "fieldInDto")
    ExampleModel mapToExample(ExampleDto exampleDto);
}
```

Dependencies:
```
<dependency>
	<groupId>org.projectlombok</groupId>
	<artifactId>lombok</artifactId>
	<version>1.18.16</version>
</dependency>
<dependency>
	<groupId>org.mapstruct</groupId>
	<artifactId>mapstruct</artifactId>
	<version>1.4.1.Final</version>
</dependency>
```

Plugin configuration:
```
<plugin>
	<groupId>org.apache.maven.plugins</groupId>
	<artifactId>maven-compiler-plugin</artifactId>
	<version>3.8.0</version>
	<configuration>
		<source>11</source>
		<target>11</target>
		<release>11</release>
		<annotationProcessorPaths>
			<path>
				<groupId>org.mapstruct</groupId>
				<artifactId>mapstruct-processor</artifactId>
				<version>1.4.1.Final</version>
			</path>
			<path>
				<groupId>org.projectlombok</groupId>
				<artifactId>lombok</artifactId>
				<version>1.18.16</version>
			</path>
		</annotationProcessorPaths>
	</configuration>
</plugin>
```

Compilation error:
```
No property named "fieldInDto" exists in source parameter(s). Did you mean "null"?
```

More details: https://stackoverflow.com/questions/64736565/mapstruct-doesnt-recognize-field-in-mapping-simple-configuration
(I posted question on StackOverflow because I thought that my configuration is wrong. But now I know it's incompatibility of versions.)

**Comment by filiphr** [comment]
Please read the [release notes](https://projectlombok.org/changelog) from Lombok when upgrading new versions. Have a look at #2267 and #2269 as well.

You need to add the `lombok-mapstruct-binding` dependency.
