### ISSUE TITLE
Ambiguous mapping methods when upgrading to Mapstruct 1.5.0.RC1

### ISSUE THREAD

**Issue by saw303** [mapstruct/mapstruct#2840]
When upgrading from Mapstruct 1.4.2 to 1.5.0.RC1 I get _Ambiguous mapping methods_ error.

Given the following MappingConfiguration I want to make use of the support of the new Jakarta annotations.

```java
@MapperConfig(
    componentModel = "jakarta",
    unmappedTargetPolicy = ReportingPolicy.ERROR,
    injectionStrategy = InjectionStrategy.CONSTRUCTOR,
    nullValueCheckStrategy = NullValueCheckStrategy.ALWAYS,
    nullValuePropertyMappingStrategy = NullValuePropertyMappingStrategy.IGNORE)
public class MicronautMappingConfig {}
```

The following mapper maps `Short` and `Integer` to their primitive value which used to work in Mapstruct 1.4.2

```java
@Mapper(config = MicronautMappingConfig.class)
public interface NumberousMapper {

    NumberDto toNumberDto(Short shortValue, Integer intValue);

    default int toInt(Number number) {
        return number.intValue();
    }

    default short toShort(Number number) {
        return number.shortValue();
    }
}

class NumberDto {

    private int intValue;
    private short shortValue;

    public int getIntValue() {
        return intValue;
    }

    public void setIntValue(int intValue) {
        this.intValue = intValue;
    }

    public short getShortValue() {
        return shortValue;
    }

    public void setShortValue(short shortValue) {
        this.shortValue = shortValue;
    }
}
```

With Mapstruct 1.5.0.RC1 I get the following error

```
NumberousMapper.java:8: error: Ambiguous mapping methods found for mapping property "Integer intValue" to int: int toInt(Number number), short toShort(Number number). See https://mapstruct.org/faq/#ambiguous for more info.
    NumberDto toNumberDto(Short shortValue, Integer intValue);
              ^
```

**Comment by filiphr** [comment]
It is weird how this used to work, because we have #1216 for a similar scenario. We are going to investigate it

**Comment by filiphr** [comment]
I am happy to announce that we have managed to find the root cause for this problem and we have a pending fix in #3032

**Comment by saw303** [comment]
@filiphr that's amazing news! Thank you

Any indication when 1.6.0 is GA?

**Comment by filiphr** [comment]
@saw303 for 1.6 we still do not have an Alpha / Beta release that would take a while. However, I would like to have a 1.5.3 released in the next 2 weeks. There are 2 PRs (one of them being the fix for this issue and 2 other ones like this one 😄) that are left for review before we have everything that we want for 1.5.3.
