### ISSUE TITLE
Mapstruct + Lombok failed Gradle compilation

### ISSUE THREAD

**Issue by vvedharaju** [mapstruct/mapstruct#1703]
In a work project, I am using the Lombok @Data annotation for all getter/setter generation. I'm running into issues with compiling with gradle when using MapStruct in conjunction.

Note: I don't have issues when building directly from Eclipse.

I have the following build.gradle:

```
buildscript {
	ext {
		springBootVersion = '2.1.2.RELEASE'
	}
	repositories {
		mavenCentral()
	}
	dependencies {
		classpath("org.springframework.boot:spring-boot-gradle-plugin:${springBootVersion}")
	}
}

plugins {
  id 'net.ltgt.apt' version '0.15'
}

apply plugin: 'java'
apply plugin: 'eclipse-wtp'
apply plugin: 'org.springframework.boot'
apply plugin: 'io.spring.dependency-management'
apply plugin: 'net.ltgt.apt-eclipse'

group = 'org.vbts'
version = '0.0.1-SNAPSHOT'
sourceCompatibility = '1.8'

repositories {
	mavenCentral()
}

dependencies {
	implementation 'org.springframework.boot:spring-boot-starter-actuator'
	implementation 'org.springframework.boot:spring-boot-starter-data-jdbc'
	implementation 'org.springframework.boot:spring-boot-starter-aop'
	implementation 'org.springframework.boot:spring-boot-starter-web'
	implementation 'org.flywaydb:flyway-core'
	implementation 'org.mindrot:jbcrypt:0.3m'
	implementation 'io.jsonwebtoken:jjwt:0.7.0'

	
		
	runtimeOnly 'org.springframework.boot:spring-boot-devtools'
	runtimeOnly 'org.postgresql:postgresql'
	
	compileOnly 'org.mapstruct:mapstruct-jdk8:1.2.0.Beta1'	
	compileOnly 'org.projectlombok:lombok:1.16.12'
	
	annotationProcessor 'org.projectlombok:lombok:1.16.12'
	annotationProcessor 'org.mapstruct:mapstruct-processor:1.2.0.Beta1'
	
	testImplementation 'org.springframework.boot:spring-boot-starter-test'
}
```

I'm able to get this working in eclipse but unable to get a direct gradle build to compile. When running `gradlew clean build` I get the following errors:

```
C:\Users\vedha\Desktop\ums>gradlew clean build

> Task :compileJava FAILED
C:\Users\vedha\Desktop\ums\src\main\java\org\vbts\ums\organization\mOrganization
Mapper.java:9: error: Unknown property "orgId" in return type.
        @Mapping(target = "orgId", ignore = true)
        ^
C:\Users\vedha\Desktop\ums\src\main\java\org\vbts\ums\organization\mOrganization
Mapper.java:15: error: Unknown property "defaultLocation" in return type.
        @Mapping(target = "defaultLocation", ignore = true)
        ^
C:\Users\vedha\Desktop\ums\src\main\java\org\vbts\ums\account\mAccountMapper.jav
a:9: error: Unknown property "accountId" in return type.
        @Mapping(target = "accountId", ignore = true)
        ^
3 errors

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileJava'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug
option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 2s
2 actionable tasks: 2 executed
```

Please advise.

**Comment by hsteidel** [comment]
I'm currently evaluating Mapstruct for my project and I ran into the same issue. I was able to get this to work with Gradle 5.0 by using the Lombok plugin instead of a dependency:

```
buildscript {
    ext {
        springBootVersion = '2.1.2.RELEASE'
        mapstructVersion = "1.2.0.Final"
        lombokVersion = "1.18.0"
    }
    repositories {
        mavenCentral()
        maven {
            url "https://plugins.gradle.org/m2/"
        }
    }
    dependencies {
        classpath("org.springframework.boot:spring-boot-gradle-plugin:${springBootVersion}")
    }
}

plugins {
    id 'net.ltgt.apt' version '0.19'
    id 'io.franzbecker.gradle-lombok' version '1.14'
}

apply plugin: 'java'
apply plugin: 'org.springframework.boot'
apply plugin: 'io.spring.dependency-management'


compileJava {
    options.compilerArgs = [
            '-Amapstruct.unmappedTargetPolicy=IGNORE',
    ]
}

sourceCompatibility = '1.8'

repositories {
    mavenCentral()
}


dependencies {

    compile "org.mapstruct:mapstruct-jdk8:${mapstructVersion}"
    apt "org.mapstruct:mapstruct-processor:${mapstructVersion}"
    compile "org.mapstruct:mapstruct:${mapstructVersion}", "org.projectlombok:lombok:${lombokVersion}"


    implementation 'org.springframework.boot:spring-boot-starter-web'
}

```

**Comment by filiphr** [comment]
@vvedharaju you are using Lombok 1.16.2. MapStruct and Lombok work nicely together since Lombok 1.16.14. See [Can I use MapStruct together with Project Lombok?](http://mapstruct.org/faq/#Can-I-use-MapStruct-together-with-Project-Lombok).

@hsteidel for you it didn't work when you put lombok under the `apt` scope? That should have worked.

I am going to close this issue, but if you think we need to do something please let us know
