### ISSUE TITLE
MapStruct 1.3.0.Final generates syntactically incorrect mapper when expression is used in nested property mapping.

### ISSUE THREAD

**Issue by mabilalmirza** [mapstruct/mapstruct#1829]
MapStruct 1.3.0.Final generates mapper implementation with syntax error when a nested object property of target is mapped with expression which accesses deeply nested property of source. This thing works fine in MapStruct 1.1.0.Final.

```
@Mapper
public interface SecondMapper {
    @Mapping(target = "root", source = "root.name")
    @Mapping(target = "description", source = "companion.description")
    @Mapping(target = "otherUnit.description", source = "companion.description")
    @Mapping(target = "otherUnit.child", source = "root.rootChild.childName")
    @Mapping(target = "otherUnit.decendent", source = "root.rootChild.rootDecendent.decendentName")
    @Mapping(target = "otherUnit.another",
            expression = "java(root.getRootChild().getRootDecendent().getDecendentName() + \"_Postfix\")")
    public OneUnit mapUnit(Root root, Companion companion);
}
```
Where structure of source and target is same as describe in mapping.

Generated Mapper is as below.

```
public class SecondMapperImpl implements SecondMapper {

    @Override
    public OneUnit mapUnit(Root root, Companion companion) {
        if ( root == null && companion == null ) {
            return null;
        }

        OneUnit oneUnit = new OneUnit();

        if ( root != null ) {
            if ( root.getRootChild() != null ) {
                if ( oneUnit.getOtherUnit() == null ) {
                    oneUnit.setOtherUnit( new OtherUnit() );
                }
                rootChildToOtherUnit( root.getRootChild(), oneUnit.getOtherUnit() );
            }
            oneUnit.setRoot( root.getName() );
        }
        if ( companion != null ) {
            if ( oneUnit.getOtherUnit() == null ) {
                oneUnit.setOtherUnit( new OtherUnit() );
            }
            companionToOtherUnit( companion, oneUnit.getOtherUnit() );
            oneUnit.setDescription( companion.getDescription() );
        }

        return oneUnit;
    }

    protected void companionToOtherUnit(Companion companion, OtherUnit mappingTarget) {
        if ( companion == null ) {
            return;
        }

        mappingTarget.setDescription( companion.getDescription() );

        mappingTarget.setAnother( root.getRootChild().getRootDecendent().getDecendentName() + "_Postfix" );
    }

    private String rootChildRootDecendentDecendentName(RootChild rootChild) {
        if ( rootChild == null ) {
            return null;
        }
        RootDecendent rootDecendent = rootChild.getRootDecendent();
        if ( rootDecendent == null ) {
            return null;
        }
        String decendentName = rootDecendent.getDecendentName();
        if ( decendentName == null ) {
            return null;
        }
        return decendentName;
    }

    protected void rootChildToOtherUnit(RootChild rootChild, OtherUnit mappingTarget) {
        if ( rootChild == null ) {
            return;
        }

        mappingTarget.setChild( rootChild.getChildName() );
        mappingTarget.setDecendent( rootChildRootDecendentDecendentName( rootChild ) );

        mappingTarget.setAnother( root.getRootChild().getRootDecendent().getDecendentName() + "_Postfix" );
    }
}
```

In this generated implementation, compiler complains that reference of root is not found in `generated companionToOtherUnit` method, and `rootChildToOtherUnit` methods. This was working fine with v1.1.0.Final.

Please see [this repo](https://github.com/mabilalmirza/mapstruct-expression-nested-object) created to demostrate this issue.
- Branch [mapstruct-1.1.0.Final](https://github.com/mabilalmirza/mapstruct-expression-nested-object/tree/mapstruct-1.1.0.Final) is getting compiled successfully and passing the test cases.
- Branc [mapstruct-1.3.0.Final](https://github.com/mabilalmirza/mapstruct-expression-nested-object/tree/mapstruct-1.3.0.Final) generates implementation with following syntax errors.

```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.1:compile (default-compile) on project mapstruct-expression-nested-object: Compilation failure: Compilation failure:
[ERROR] /***********/mapstruct-expression-nested-object/target/generated-sources/annotations/demo/second/SecondMapperImpl.java:[54,35] cannot find symbol
[ERROR] symbol:   variable root
[ERROR] location: class demo.second.SecondMapperImpl
[ERROR] /***********/mapstruct-expression-nested-object/target/generated-sources/annotations/demo/second/SecondMapperImpl.java:[80,35] cannot find symbol
[ERROR] symbol:   variable root
[ERROR] location: class demo.second.SecondMapperImpl
```

**Comment by sjaakd** [comment]
@mabilalmirza thanks for reporting.. I'll have a look asap.

**Comment by cedricdev** [comment]
I have exactly the same problem

**Comment by mabilalmirza** [comment]
Issue remains in `1.3.1.Final`. Issue [repo](https://github.com/mabilalmirza/mapstruct-expression-nested-object) has been updated with [mapstruct-1.3.1.Final](https://github.com/mabilalmirza/mapstruct-expression-nested-object/tree/mapstruct-1.3.1.Final) branch.

**Comment by mabilalmirza** [comment]
> I have exactly the same problem with 1.2.0 and 1.3.0. i must use 1.1.0 but i would like to use lombok. i'm blocked

@cedricdev , In have been using Lombok v1.16.16 and MapStruct 1.1.0.Final (with maven as below). May be you can give it a try.

```xml
<lombok.version>1.16.16</lombok.version>
<org.mapstruct.version>1.1.0.Final</org.mapstruct.version>

...

<dependency>
	<groupId>org.projectlombok</groupId>
	<artifactId>lombok</artifactId>
	<version>${lombok.version}</version>
	<scope>provided</scope>
</dependency>

<dependency>
	<groupId>org.mapstruct</groupId>
	<artifactId>mapstruct-jdk8</artifactId>
	<version>${org.mapstruct.version}</version>
</dependency>

<dependency>
	<groupId>org.mapstruct</groupId>
	<artifactId>mapstruct-processor</artifactId>
	<version>${org.mapstruct.version}</version>
	<scope>provided</scope>
</dependency>
```

**Comment by Calle-Lo** [comment]
Is there any progress here @sjaakd ?

**Comment by awilhelmer** [comment]
I just ran into the same problem on 1.3.1.final

**Comment by jonybuzz** [comment]
**Workaround**: use a java expression in the conflicting mapping source. Like:
`  @Mapping(target = "otherUnit.child", expression = "java(root.getRootChild().getChildName())"`
