### PR TITLE
#2840, #2913, #2921: MethodMatcher should not match widening methods

### LINKED ISSUE #2840: Ambiguous mapping methods when upgrading to Mapstruct 1.5.0.RC1
When upgrading from Mapstruct 1.4.2 to 1.5.0.RC1 I get _Ambiguous mapping methods_ error.

Given the following MappingConfiguration I want to make use of the support of the new Jakarta annotations.

```java
@MapperConfig(
    componentModel = "jakarta",
    unmappedTargetPolicy = ReportingPolicy.ERROR,
    injectionStrategy = InjectionStrategy.CONSTRUCTOR,
    nullValueCheckStrategy = NullValueCheckStrategy.ALWAYS,
    nullValuePropertyMappingStrategy = NullValuePropertyMappingStrategy.IGNORE)
public class MicronautMappingConfig {}
```

The following mapper maps `Short` and `Integer` to their primitive value which used to work in Mapstruct 1.4.2

```java
@Mapper(config = MicronautMappingConfig.class)
public interface NumberousMapper {

    NumberDto toNumberDto(Short shortValue, Integer intValue);

    default int toInt(Number number) {
        return number.intValue();
    }

    default short toShort(Number number) {
        return number.shortValue();
    }
}

class NumberDto {

    private int intValue;
    private short shortValue;

    public int getIntValue() {
        return intValue;
    }

    public void setIntValue(int intValue) {
        this.intValue = intValue;
    }

    public short getShortValue() {
        return shortValue;
    }

    public void setShortValue(short shortValue) {
        this.shortValue = shortValue;
    }
}
```

With Mapstruct 1.5.0.RC1 I get the following error

```
NumberousMapper.java:8: error: Ambiguous mapping methods found for mapping property "Integer intValue" to int: int toInt(Number number), short toShort(Number number). See https://mapstruct.org/faq/#ambiguous for more info.
    NumberDto toNumberDto(Short shortValue, Integer intValue);
              ^
```

### LINKED ISSUE #2913: Conversion of BigDecimal to primitive double wrong with 1.5.2
After migrating from 1.4.2 to 1.5.2 a test failed. The result from BigDecimal to double is not the same anymore. Please have a look. Thanks.

https://github.com/urswiss/mapstruct-bigdecimal-to-double

### LINKED ISSUE #2921: Upgrade from 1.4.1 to 1.5.2 broke primitive to wrapper classes mapping
We had a mapper that mapped `Integer` to `int` properties from an internal model to a dto (method1). In the same mapper we had a method that mapped from Integer to Short(method2). This method was used in an expression on a different mapping method(method3). After upgrading to 1.5.2 that method Integer->Short (method2) is now used instead of generating a proper Integer to int mapping like it did in 1.4.2(for method1). 
This is bad for values that uses more than 16 bits and very dangerous as it can pass a lot of tests.
Is there an annotation that can be put on a method to restrict it to be used only on expressions and not be picked up by mapstruct just by types?
Thanks

### PR DESCRIPTION
**Pull request by filiphr**
In the MethodMatcher we need to do a special check when the target type is primitive. The reason for that is that a Long is assignable to a primitive double. However, doing that means that information can be lost and thus we should not pick such methods. When the target type is primitive, then a method will be matched if and only if boxed equivalent of the target type is assignable to the boxed equivalent of the candidate return type.

Fixes #2840 
Fixes #2913 
Fixes #2921

### CODE REVIEW

**Review by sjaakd — APPROVED** [review]
LGTM Filip. Go ahead

File: processor/src/main/java/org/mapstruct/ap/internal/model/source/MethodMatcher.java [hunk 1]
```diff
@@ -82,6 +82,17 @@ boolean matches(List<Type> sourceTypes, Type targetType) {
         // (the relation target / target type, target type being a class)
 
         if ( !analyser.candidateReturnType.isVoid() ) {
+            if ( targetType.isPrimitive() ) {
+                // If the target type is primitive
+                // then we are going to check is its boxed equivalent
```
Comment (Zegveld) [inline processor/src/main/java/org/mapstruct/ap/internal/model/source/MethodMatcher.java:87]: typo: `check is its...` should be `check if its...`

**Review by Zegveld — APPROVED** [review]
Looks good to me, did find a single typo. ;)

**Comment by filiphr** [comment]
Thanks for the reviews
