### ISSUE TITLE
Possible regression: Wrong mapper code generation when using Builder 

### ISSUE THREAD

**Issue by juliojgd** [mapstruct/mapstruct#2195]
This is a issue that happens in **1.3.1.Final** and **1.4.0.CR1** but works OK in 1.3.0.Final. So I guess is some kind of regression.

I include a simple project [here](https://github.com/juliojgd/mapstruct_tests) using Java 8 and Lombok 1.18.12 that:
Builds **OK** when:
`$ mvn clean install -Dorg.mapstruct.version=1.3.0.Final`

But generated wrong mapper impl and output compilation failure when:
`$ mvn clean install -Dorg.mapstruct.version=1.3.1.Final`
and when:
`$ mvn clean install -Dorg.mapstruct.version=1.4.0.CR1`

The compilation failure is as follows:
```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.1:compile (default-compile) on project mapstructtest: Compilation failure: Compilation failure:
[ERROR] /C:/repos/mapstruct_test/juliojgd_mapstructtest/target/generated-sources/annotations/io/github/juliojgd/mapstruct/builder/mapper/BadCodeGeneratedMapperImpl.java:[52,57] incompatible types: io.github.juliojgd.mapstruct.builder.TenthRequest.Builder cannot be converted to io.github.juliojgd.mapstruct.builder.TenthRequest
```

Is this issue registered and is there any plan to fix it? In **1.3.2-SNAPSHOT** is failing also.
 Thanks in advance

**Comment by sjaakd** [comment]
Ah.. builders were introduced as part of 1.3.0.Final. Your code contains builders (lombok)? In 1.3.1.Final and 1.4.0.CR1 you can switch them off. Add: `@Mapper( builder=builder = @Builder( disableBuilder = true ))` to your mapping definition.

**Comment by juliojgd** [comment]
I provided a project that is building fine with 1.3.0.Final. But is failing
to build with 1.3.1.Final , 1.3.2-SNAPSOT and 1.4.0.CR1.

It seems to me like a regression bug.

Sjaak, we don't want to disable a feature that we use and that should work.
We'd better want to see it fixed by reporting the bug and helping to fix it
in the extent we can.

**Comment by sjaakd** [comment]
@juliojgd sorry.. I made an assumption that you accidentally triggered the builder functionality (we had a number of reports on that one: people not knowing that they had builders).. 

Thanks for the reproducer. I cloned your repo and was able to reproduce the problem. I did however need to remove an obsolete mapping (at least I assume): 

```java

    @Mapping(source = "type", target = "fifthEnum")
    @Mapping(source = "code", target = "thing9")
    @Mapping(source = "thing16", target = "fourthType.countryIso")
    @Mapping(target = "thing7", constant = "0")
//    @Mapping(target = "extraParams", source = "extraParams", qualifiedByName = "mapExtraParams")
    @BeanMapping(resultType = TenthRequest.class)
    TenthRequest getAndValidateRequest2LocationRequest(EightthRequest eightthRequest);

```

**Comment by sjaakd** [comment]
question: why do you need to define the result type for `TenthRequest`? .. MapStruct is not acting right, it is confused by having a builder pattern and a result type. So, there's something we need to fix. I spotted another problem as well, trying to get your example as a minimal reproducer.  That needs to be fixed as well. 

But the question remains.. If you change your mapper to:

```java
    @Mapping(source = "type", target = "fifthEnum")
    @Mapping(source = "code", target = "thing9")
    @Mapping(source = "thing16", target = "fourthType.countryIso")
    @Mapping(target = "thing7", constant = "0")
  //  @Mapping(target = "extraParams", source = "extraParams", qualifiedByName = "mapExtraParams") This functionality has changed. The qualifier functionality was dubious at this point. You cannot qualify an element mapping through its collection. But in your case, its not needed to help MapStruct to select the proper method. 
  //  @BeanMapping(resultType = TenthRequest.class) this is not needed, the result type is already TenthRequest . De resilttype functionality is there for if you return an interface or a common super type. It instructs MapStruct to select the proper implementation type.
    TenthRequest getAndValidateRequest2LocationRequest(EightthRequest eightthRequest);

```

It will compile as expected

**Comment by sjaakd** [comment]
Solved by means of PR. Please adapt your solution as well according to my suggestions. You still need to remove the qualified by and I would strongly advise you to also remove the `@BeanMapping(resultType = TenthRequest.class)` since it does not add anything to your solution. 

However, the latter one triggered the PR to fix cases (in pseudo) `@BeanMapping(resultType = InheritedFromTenthRequest.class)`  

Thanks for reporting.

**Comment by juliojgd** [comment]
Thank you very much @sjaakd both for the explanation and the fix. I can confirm that removing the `@BeanMapping` annotation (it was unnecesary as you guessed) it is building again with 1.3.1.Final.
We will be testing against 1.4.x SNAPSHOT's
Thanks again!
