### ISSUE TITLE
MapStruct 1.5.0.Beta1 ZonedDateTime field mapping regression

### ISSUE THREAD

**Issue by rlei** [mapstruct/mapstruct#2530]
Hi team, thanks for the hard work - 1.5.0.Beta1 looks awesome! Meanwhile I've found one regression as following:

This was working with 1.4.1.Final:

```java
package test;

import java.time.ZonedDateTime;
import org.mapstruct.Mapper;
import org.mapstruct.Mapping;

@Mapper
interface TestMapper {
  @Mapping(target = "dateTime", source = ".", dateFormat = "YYYY-MM-DD")
  Test map(String s);

  class Test {

    public ZonedDateTime getDateTime() {
      return dateTime;
    }

    public void setDateTime(ZonedDateTime dateTime) {
      this.dateTime = dateTime;
    }

    ZonedDateTime dateTime;
  }
}
```

but started to fail with 1.5.0.Beta1:
```
TestMapperImpl.java:23: error: cannot find symbol
            test.setDateTime( ZonedDateTime.parse( s, dateTimeFormatter_YYYY_MM_DD_11271985664 ) );
                                                      ^
  symbol:   variable dateTimeFormatter_YYYY_MM_DD_11271985664
  location: class TestMapperImpl
```

Compiler:
```
ᐅ javac -version
javac 11.0.11
ᐅ java -version
openjdk version "11.0.11" 2021-04-20
OpenJDK Runtime Environment AdoptOpenJDK-11.0.11+9 (build 11.0.11+9)
OpenJDK 64-Bit Server VM AdoptOpenJDK-11.0.11+9 (build 11.0.11+9, mixed mode)
```

**Comment by rlei** [comment]
p.s: 1.4.1.Final generated this mapping code:
```java
test.setDateTime( ZonedDateTime.parse( s, DateTimeFormatter.ofPattern( "YYYY-MM-DD" ) ) );
```

and 1.5.0.Beta1:
```java
test.setDateTime( ZonedDateTime.parse( s, dateTimeFormatter_YYYY_MM_DD_11271985664 ) );
```

**Comment by Zegveld** [comment]
Analysis: The ReverseConversion class does not return the required helper fields list: getRequiredHelperFields().
I'm working on a PR to fix this issue, expect it somewhere today.

**Comment by filiphr** [comment]
Thanks for reporting this @rlei and thanks for the quick fix @Zegveld
