### ISSUE TITLE
Import handling for built-in methods not fully working

### ISSUE THREAD

**Issue by gunnarmorling** [mapstruct/mapstruct#939]
For the Joda LocalDateTime <> Date conversion I needed to use FQNs, as for some reason LocalDateTime wasn't added to the list of imports of the generated class.

**Comment by sjaakd** [comment]
Ai! Need to fix!

Verstuurd vanaf mijn iPhone

**Comment by sjaakd** [comment]
Hmm. Title is a bit confusing with description. I tried to build a reproducer for the conversion.. No issue there. Then I looked through all the built-in generated code. Also no problem.

Can you be more specific?

**Comment by gunnarmorling** [comment]
Yes, take a look at `LocalDateToXmlGregorianCalendar.ftl`. The FQN `java.time.LocalDate` is given there as a workaround. It should still work when only using the simple name `LocalDate`, as the corresponding conversion class `LocalDateToXmlGregorianCalendar` adds the parameter type to the list of import types. But that import doesn't show up in the generated file.

I only had a quick look so far, I suspect it's related to a collision with Joda's type `LocalDate` with the same simple name. I believe the two types collide in the import handling mechanism somehow.

**Comment by tbrizard** [comment]
I am having a related issues after upgrading to 1.1.0.Final.  The generated source does not include all the needed imports.  For example, the following method is in the generated source (only showing pertinent code), but the `java.util.Date` class is not imported, which then causes a compilation error.

```
@Generated(
    value = "org.mapstruct.ap.MappingProcessor",
    date = "2016-12-07T13:57:28-0500",
    comments = "version: 1.1.0.Final, compiler: javac, environment: Java 1.8.0_101 (Oracle Corporation)"
)
@ApplicationScoped
public class DaoMapStructImpl implements DaoMapStruct {

. . . .

   private XMLGregorianCalendar dateToXmlGregorianCalendar( Date date ) {
        if ( date == null ) {
            return null;
        }

        try {
            GregorianCalendar c = new GregorianCalendar();
            c.setTime( date );
            return DatatypeFactory.newInstance().newXMLGregorianCalendar( c );
        }
        catch ( DatatypeConfigurationException ex ) {
            throw new RuntimeException( ex );
        }
    }

. . . .

}

```

**Comment by gunnarmorling** [comment]
Hi Tim, could you open a new issue for this, including the definition of
your mapper? Thanks!

As a workaround, you can enforce the import: @Mapper(imports=Date.class)
MyMapper { ... }

**Comment by tbrizard** [comment]
Thank you, Gunnar.  I have created https://github.com/mapstruct/mapstruct/issues/987 for the issue I am seeing.  I noted in the new issue that the work-around you mentioned unfortunately did not fix the particular issue I am seeing.
