### ISSUE TITLE
Still unable to compile with lombok 1.16.14 and mapstruct 1.2.0.Beta1

### ISSUE THREAD

**Issue by Dreijnde** [mapstruct/mapstruct#1128]
Please help! I love to use mapstruct with lombok.
I use versions lombok 1.16.14 and mapstruct 1.2.0.Beta1.

I get a long list of the following errors during compilation when adding the mapstruct processor to the maven compiler: 

```
[ERROR]  constructor Foo in enum Bar cannot be applied to given types;
[ERROR] required: no arguments
[ERROR] found: java.lang.String
[ERROR] reason: actual and formal argument lists differ in length
```

```
[ERROR] cannot find symbol
[ERROR] symbol:   method Foo()
[ERROR] location: variable filter of type Bar
```

my maven pom.xml is set up like this:

```
	<build>
		<plugins>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-compiler-plugin</artifactId>
				<version>${maven-compiler-plugin-version}</version>
				<configuration>
					<source>${maven.compiler.source}</source>
					<target>${maven.compiler.target}</target>
					<annotationProcessorPaths>
						<path>
							<groupId>org.mapstruct</groupId>
							<artifactId>mapstruct-processor</artifactId>
							<version>${mapstruct.version}</version>
						</path>
					</annotationProcessorPaths>
				</configuration>
			</plugin>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-deploy-plugin</artifactId>
				<version>${maven-deploy-plugin-version}</version>
			</plugin>
		</plugins>
	</build>
```

How i am using lombok and mapstruct:

```
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class FooDTO {

  private boolean X;
  private boolean Y;
  private String Z;

```
The noargs and allargs are needed to resolve Data with Builder

```

@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class Foo{

  private boolean X;
  private boolean Y;
  private String Z;

```
```
@Mapper
public interface Bar{
  
  Bar INSTANCE = Mappers.getMapper(Bar.class);
  
  Foo fooDtoToFoo(FooDTO fooDto);
}

```

**Comment by Dreijnde** [comment]
Removing the annotation processor from the pom.xml seems to resolve the issue. 

Does 1.2.0.Beta1 not need the processor anymore?

**Comment by filiphr** [comment]
@Dreijnde of course it does. When you configure the maven compiler with the `annotationProcessorPaths` then it only uses the Annotation Processors defined in those paths (see [here](https://maven.apache.org/plugins/maven-compiler-plugin/compile-mojo.html#annotationProcessorPaths)). If you remove the `annotationProcessorPaths` then the maven compiler picks up all Annotation Processors on your classpath. For you it most probably works, because you have `mapstruct-processor` as a maven dependency.

The same issue was raised in #1116, you can have a look ok at this comment https://github.com/mapstruct/mapstruct/issues/1116#issuecomment-283982109 as well.

The solution is either add lombok to the `annotationProcessorPaths` or do not use them and add the needed processor as maven dependecies
