### ISSUE TITLE
1.5.0.Beta2: No longer working with Hibernate JPA Metamodel Generator

### ISSUE THREAD

**Issue by daniel-shuy** [mapstruct/mapstruct#2751]
- [x] Is this an issue (and hence not a question)? 

MapStruct `1.5.0.Beta2` somehow breaks Maven compilation with Hibernate JPA Metamodel Generator (`org.hibernate:hibernate-jpamodelgen`). The only thing I have changed is the MapStruct version (it works fine with MapStruct `1.4.2.Final`).

Compilation fails with `cannot find symbol`, the generated classes are not discovered.

I suspect this has something to do with the annotation processing sequence, as the generated classes are present in `target/generated-sources/annotations`.

**Comment by filiphr** [comment]
Can you please provide a minimal project that is showcasing the problem? I don't see anything that would cause the problem you are having

**Comment by daniel-shuy** [comment]
Sorry, turns out it has nothing to do with Hibernate JPA Static Metamodel Generator and was instead due to `1.5.0.Beta2` being more strict with unknown ignores.
