### PR TITLE
#2530: bugfix for ReverseConversion with SupportingFields.

### LINKED ISSUE #2530: MapStruct 1.5.0.Beta1 ZonedDateTime field mapping regression
Hi team, thanks for the hard work - 1.5.0.Beta1 looks awesome! Meanwhile I've found one regression as following:

This was working with 1.4.1.Final:

```java
package test;

import java.time.ZonedDateTime;
import org.mapstruct.Mapper;
import org.mapstruct.Mapping;

@Mapper
interface TestMapper {
  @Mapping(target = "dateTime", source = ".", dateFormat = "YYYY-MM-DD")
  Test map(String s);

  class Test {

    public ZonedDateTime getDateTime() {
      return dateTime;
    }

    public void setDateTime(ZonedDateTime dateTime) {
      this.dateTime = dateTime;
    }

    ZonedDateTime dateTime;
  }
}
```

but started to fail with 1.5.0.Beta1:
```
TestMapperImpl.java:23: error: cannot find symbol
            test.setDateTime( ZonedDateTime.parse( s, dateTimeFormatter_YYYY_MM_DD_11271985664 ) );
                                                      ^
  symbol:   variable dateTimeFormatter_YYYY_MM_DD_11271985664
  location: class TestMapperImpl
```

Compiler:
```
ᐅ javac -version
javac 11.0.11
ᐅ java -version
openjdk version "11.0.11" 2021-04-20
OpenJDK Runtime Environment AdoptOpenJDK-11.0.11+9 (build 11.0.11+9)
OpenJDK 64-Bit Server VM AdoptOpenJDK-11.0.11+9 (build 11.0.11+9, mixed mode)
```

### PR DESCRIPTION
**Pull request by Zegveld**
Fixes #2530

### CODE REVIEW

**Comment by filiphr** [comment]
Good catch and good PR @Zegveld. I've let the CI run. On first sight it looks all good. Will check it and merge it next week once I am back from holidays

**Comment by Zegveld** [comment]
Seems like a network connection issue why the CI/Windows failed:
`Transfer failed for https://repo.maven.apache.org/maven2/org/jruby/jruby-complete/9.2.17.0/jruby-complete-9.2.17.0.jar: Connection reset -> [Help 1]`
Good to see that the others succeed. This confirms my suspicion that my local environment has some issues. Had a weird reason why the integration-test failed locally.

**Comment by filiphr** [comment]
Thanks for the PR @Zegveld
