### ISSUE TITLE
Missing explicit import to nested enum

### ISSUE THREAD

**Issue by bgK** [mapstruct/mapstruct#2948]
Given a source class,
```java
public record TestEntity() {}
```

A target class referencing a nested enum,
```java
public class EnumHolder {
    public enum TestEnum {
        VALUE_1,
        VALUE_2,
    }
}

public record TestDto(TestEnum data) {}
```

A mapper with a java expression referencing a nested enum constant and an explicit import,
```java
@Mapper(imports = TestEnum.class)
public interface TestMapper {
    @Mapping(target = "data", expression = "java(TestEnum.VALUE_1)")
    TestDto map(TestEntity entity);
}
```

When compiling with mapstruct 1.5.2, the following error occurs: `TestMapperImpl.java:[21,36] cannot find symbol: variable TestEnum`
When inspecting the generated mapper source, the import is missing for the enum.
This used to work with Mapstruct 1.4.1.

This is the reproduction case packaged as a Maven project:
[mapstruct-import-java-nested-enum.zip](https://github.com/mapstruct/mapstruct/files/9233009/mapstruct-import-java-nested-enum.zip)

**Comment by Zegveld** [comment]
an improvement here would be to use
```
@Mapping(target = "data", constant = "VALUE_1")
```

The cause might be that this is a nested enum. There has been a change to only import top-level classes. With these explicit imports it still should do that import instead. 

This is related to issue #2945

**Comment by filiphr** [comment]
Thanks again @bgK for the detailed examples. I've put this on 1.6 with the same state as #2945. We need to be a bit smarter here I think.

**Comment by filiphr** [comment]
After an analysis of this issue, I realized that this is identical to #2897. There are 2 workarounds for this particular problem:

* Use parent class. Note: once we fix the issue this workaround will no longer be possible.
```java
@Mapping(target = "data", expression = "java(EnumHolder .TestEnum.VALUE_1)")
```
* Do not use `Mapper#imports` but rather use `constant`. This is only applicable for enums
```
@Mapping(target = "data", constant = "VALUE_1")
```
